#! /usr/bin/env bash

set -e
set -o pipefail
set -u

printf '>seq\nAAAAAAAAAAAAACCCCCCCCCCAAAAAAAAAAAAAAAAAAAAAAA\n' > isolate1.fa
printf '>seq\nAAAAAAAAAAAAACCCCGCCCCCAAAAAAAAAAAAAAAAAAAA\n' > isolate2.fa
printf '>seq\nAAAAAAAAAAAAACGTTTGGCGCCGGAAAAAAAAAAAAAAAAAAAAAAAAAA\n' > isolate3.fa
printf '>seq\nAAAAAAAAAAAAATGTTTTTTGGCCGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' > isolate4.fa
printf '>seq\nAAAAAAAAAAAAATGTTTTTTTTGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' > isolate5.fa

